### ISSUE TITLE
diffrent first_filter_stride

### ISSUE THREAD

**Issue by Ldoun** [akaraspt/tinysleepnet#2]
In the paper it says the stride of first filter is sampling_rate / 4   but in the model.py stride of first filter is sampling rate / 16 is there a reason for it?
def build_cnn(self):
        first_filter_size = int(self.config["sampling_rate"] / 2.0)
        first_filter_stride = int(self.config["sampling_rate"] / 16.0)

[first_filter_stride](https://github.com/akaraspt/tinysleepnet/blob/main/model.py#L221)

**Comment by akaraspt** [comment]
It seems that it is a typo in the figure. It should be sampling_rate / 16.

**Comment by Ldoun** [comment]
got it
thanks for the reply! 👍
