### ISSUE TITLE
Excellent project！ 

### ISSUE THREAD

**Issue by SMACY2017** [akaraspt/tinysleepnet#6]
Excellent project！
I have followed your instructions and successfully run the code.
Thank you 
![图片](https://user-images.githubusercontent.com/55419749/125183583-3899e880-e24a-11eb-8b13-9e270ba3349e.png)

**Comment by SongLin99** [comment]
Hi bro：
I`m studying this project as my graduation paper， But  I have many questions ，could  you please help me?

**Comment by SongLin99** [comment]
> Excellent project！ I have followed your instructions and successfully run the code. Thank you ![图片](https://user-images.githubusercontent.com/55419749/125183583-3899e880-e24a-11eb-8b13-9e270ba3349e.png)
Hi bro：
I`m studying this project as my graduation paper， But I have many questions ，could you please help me?

**Comment by SMACY2017** [comment]
> Hi bro： I`m studying this project as my graduation paper， But I have many questions ，could you please help me?

so what are your specific questions? maybe you can put them here. the owener and i might  be able to provide some help

**Comment by SongLin99** [comment]
I don`t know why the input_size of LSTM is 2048 
why not other numbers

**Comment by akaraspt** [comment]
@SongLin99 The number of units in each layer is from the best results from our experiments. The details are not included in the paper.
