### ISSUE TITLE
Question on predict.py

### ISSUE THREAD

**Issue by sajjadkarimi91** [akaraspt/tinysleepnet#7]
I couldn't find the method evaluate_aug in predict.py
However the training settings are "augment_seq": True,   "augment_signal_full": True, test epochs run with "model.evaluate" instead of  "model.evaluate_aug".
Is there a specific reason?

            if (config.get('augment_signal') is not None) and config['augment_signal']:
                        # Evaluate
                        test_outs = model.evaluate_aug(test_minibatch_fn)
                    else:
                        # Evaluate
                        test_outs = model.evaluate(test_minibatch_fn)

**Comment by akaraspt** [comment]
`evaluate_aug` was implemented to test whether the old augmentation works, which is no longer use. It has already been included in the `evaluate`. So you can ignore it.
